import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class HomeService {

  private _apiUrl: string;

  constructor() {
    this._apiUrl = '';
  }

  public locations(): Promise<Array<string>> {
    return new Promise((resolve, reject) => {
      resolve(this._mock_locations)
    })
  }

  private _mock_locations = [
    "Abrantes",
    "Acacias",
    "Adelfas",
    "Aeropuerto",
    "Aguilas",
    "Alameda de Osuna",
    "Almagro",
    "Almenara",
    "Almendrales",
    "Aluche",
    "Ambroz",
    "Amposta",
    "Apostol Santiago",
    "Arapiles",
    "Aravaca",
    "Arcos",
    "Argüelles",
    "Atocha",
    "Bellas Vistas",
    "Berruguete",
    "Buenavista",
    "Butarque",
    "Campamento",
    "Canillas",
    "Canillejas",
    "Casa de Campo",
    "Casco Histórico de Barajas",
    "Casco Histórico de Vallecas",
    "Casco Histórico de Vicálvaro",
    "Castellana",
    "Castilla",
    "Castillejos",
    "Chopera",
    "Ciudad Jardín",
    "Ciudad Universitaria",
    "Colina",
    "Comillas",
    "Concepción",
    "Corralejos",
    "Cortes",
    "Costillares",
    "Cuatro Caminos",
    "Cuatro Vientos",
    "Cármenes",
    "Delicias",
    "El Goloso",
    "El Plantío",
    "El Viso",
    "Embajadores",
    "Entrevías",
    "Estrella",
    "Fontarrón",
    "Fuente del Berro",
    "Fuentelareina",
    "Gaztambide",
    "Goya",
    "Guindalera",
    "Hellín",
    "Hispanoamérica",
    "Ibiza",
    "Imperial",
    "Jerónimos",
    "Justicia",
    "La Paz",
    "Legazpi",
    "Lista",
    "Los Angeles",
    "Los Rosales",
    "Lucero",
    "Marroquina",
    "Media Legua",
    "Mirasierra",
    "Moscardó",
    "Niño Jesús",
    "Nueva España",
    "Numancia",
    "Opañel",
    "Orcasitas",
    "Orcasur",
    "Pacífico",
    "Palacio",
    "Palomas",
    "Palomeras Bajas",
    "Palomeras Sureste",
    "Palos de Moguer",
    "Pavones",
    "Peñagrande",
    "Pilar",
    "Pinar del Rey",
    "Piovera",
    "Portazgo",
    "Pradolongo",
    "Prosperidad",
    "Pueblo Nuevo",
    "Puerta Bonita",
    "Puerta del Angel",
    "Quintana",
    "Recoletos",
    "Rejas",
    "Rios Rosas",
    "Rosas",
    "Salvador",
    "San Andrés",
    "San Cristobal",
    "San Diego",
    "San Fermín",
    "San Isidro",
    "San Juan Bautista",
    "San Pascual",
    "Santa Eugenia",
    "Simancas",
    "Sol",
    "Timón",
    "Trafalgar",
    "Universidad",
    "Valdeacederas",
    "Valdefuentes",
    "Valdemarín",
    "Valdezarza",
    "Vallehermoso",
    "Valverde",
    "Ventas",
    "Vinateros",
    "Vista Alegre",
    "Zofío"
  ]

}
