export enum PropertyType {
  APARTMENT = 'Apartment',
  HOUSE = 'House',
  OTHER = 'Other',
  TOWNHOUSE = 'Townhouse',
  CONDOMINIUM = 'Condominium',
  BED_AND_BREAKFAST = 'Bed & Breakfast',
  DORM = 'Dorm',
  LOFT = 'Loft',
  CHALET = 'Chalet',
  SERVICED_APARTMENT = 'Serviced apartment',
  EARTH_HOUSE = 'Earth House',
  GUESTHOUSE = 'Guesthouse',
  CASA_PARTICULAR = 'Casa particular',
  BOUTIQUE_HOTEL = 'Boutique hotel',
  HOSTEL = 'Hostel',
  GUEST_SUITE = 'Guest suite',
  CAMPERRV = 'CamperRV',
  VILLA = 'Villa',
  TIMESHARE = 'Timeshare',
  TENT = 'Tent',
  BOAT = 'Boat',
  BUNGALOW = 'Bungalow',
}
